Fix initialization of options parser in unit test.
After removing -s option from gpsegstart, this unit test started failing
with curious error:

Stderr:
Usage: gpunit [--help] [options]

gpunit: error: no such option: -s

======================================================================
ERROR: Test Suite Name|programs.test.unit.test_cluster_clsrecoversegment|Test Case Name|test_output_segments_in_change_tracking_disabled_should_print_failed_segments|Test Details|
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/heikki/git-sandbox-gpdb/master/gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment.py", line 16, in setUp
    (options, _) = raw_options.parse_args()
  File "/usr/lib/python2.7/optparse.py", line 1402, in parse_args
    self.error(str(err))
  File "/usr/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/usr/lib/python2.7/optparse.py", line 1574, in exit
    sys.exit(status)
SystemExit: 2

It turns out that the unit test was passing the command-line options from
the gpunit invocation, to the options parser of the gpsegstart command. It
was accidental that it ever worked, because gpsegstart also happened to have
a -s option, like gpunit did. Now that the option was removed, the gpsegstart
options parser started to fail.

To fix, explicitly pass "no command-line arguments" to the gpsegstart
options parser, so that it doesn't pick up the args from the gpunit
invocation.